databases:
  - name: busify-db
    plan: free
    databaseName: busify
    user: busify_user

services:
  - type: web
    name: busify
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn bus_ticket.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: busify-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.11.6"
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
      - key: RENDER_EXTERNAL_HOSTNAME
        fromService:
          type: web
          name: busify
          property: host
