# Generated by Django 4.2.29 on 2026-04-04 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='amenities',
            field=models.JSONField(blank=True, default=dict, help_text='e.g. {"ac": false, "wifi": false, "charging": false, "water": false, "blanket": false}'),
        ),
        migrations.AddField(
            model_name='bus',
            name='bus_type',
            field=models.CharField(choices=[('ORDINARY', 'Ordinary'), ('EXPRESS', 'Express'), ('SUPER_DELUXE', 'Super Deluxe'), ('AC', 'AC'), ('SLEEPER', 'Sleeper')], default='ORDINARY', max_length=20),
        ),
        migrations.AddField(
            model_name='bus',
            name='layout_type',
            field=models.CharField(choices=[('2x2', '2x2'), ('2x3', '2x3'), ('SLEEPER', 'Sleeper')], default='2x2', max_length=10),
        ),
        migrations.AddField(
            model_name='bus',
            name='operator_type',
            field=models.CharField(choices=[('GOVT', 'Government'), ('PRIVATE', 'Private'), ('LOCAL', 'Local')], default='GOVT', max_length=10),
        ),
        migrations.AddField(
            model_name='bus',
            name='total_seats',
            field=models.PositiveIntegerField(default=40),
        ),
        migrations.AddField(
            model_name='stop',
            name='arrival_offset_minutes',
            field=models.IntegerField(default=0),
        ),
    ]
