# Generated by Django 4.2.29 on 2026-04-04 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('routes', '0002_bus_amenities_bus_bus_type_bus_layout_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journey_date', models.DateField()),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('base_fare', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tatkal_fare', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tatkal_quota_pct', models.PositiveIntegerField(default=30)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('DEPARTED', 'Departed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='routes.bus')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='routes.route')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=5)),
                ('row', models.PositiveIntegerField()),
                ('column', models.PositiveIntegerField()),
                ('seat_type', models.CharField(choices=[('WINDOW', 'Window'), ('AISLE', 'Aisle'), ('MIDDLE', 'Middle'), ('LOWER_BERTH', 'Lower Berth'), ('UPPER_BERTH', 'Upper Berth')], max_length=20)),
                ('is_ladies_reserved', models.BooleanField(default=False)),
                ('is_tatkal', models.BooleanField(default=False)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='routes.bus')),
            ],
        ),
        migrations.CreateModel(
            name='SeatInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('ON_HOLD', 'On Hold'), ('BOOKED', 'Booked'), ('EXPIRED', 'Expired')], default='AVAILABLE', max_length=20)),
                ('held_by_session', models.CharField(blank=True, max_length=100, null=True)),
                ('hold_expires_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seat_inventory', to='bookings.booking')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='inventory.schedule')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='inventory.seat')),
            ],
            options={
                'unique_together': {('schedule', 'seat')},
            },
        ),
    ]
