# Generated by Django 4.2.29 on 2026-04-23 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('routes', '0002_bus_amenities_bus_bus_type_bus_layout_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='routes.bus')),
            ],
            options={
                'ordering': ['-updated_at'],
                'get_latest_by': 'updated_at',
            },
        ),
    ]
