# Generated by Django 4.2.29 on 2026-04-04 06:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('routes', '0002_bus_amenities_bus_bus_type_bus_layout_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('passenger_name', models.CharField(max_length=200)),
                ('passenger_phone', models.CharField(max_length=15)),
                ('passenger_email', models.EmailField(blank=True, max_length=254)),
                ('booking_type', models.CharField(choices=[('ADVANCE', 'Advance'), ('ON_BUS', 'On Bus')], default='ADVANCE', max_length=10)),
                ('is_tatkal', models.BooleanField(default=False)),
                ('total_fare', models.DecimalField(decimal_places=2, max_digits=8)),
                ('payment_id', models.CharField(blank=True, max_length=200)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10)),
                ('from_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings_from', to='routes.stop')),
            ],
        ),
    ]
