# Generated by Django 4.2.29 on 2026-04-04 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('bookings', '0001_initial'),
        ('routes', '0002_bus_amenities_bus_bus_type_bus_layout_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='inventory.schedule'),
        ),
        migrations.AddField(
            model_name='booking',
            name='seats',
            field=models.ManyToManyField(related_name='bookings', to='inventory.seat'),
        ),
        migrations.AddField(
            model_name='booking',
            name='to_stop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings_to', to='routes.stop'),
        ),
    ]
