# Generated by Django 4.2.29 on 2026-03-30 13:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('passenger_name', models.CharField(max_length=255)),
                ('passenger_phone', models.CharField(max_length=15)),
                ('fare_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('payment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='tickets/qr/')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='tickets/pdf/')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='routes.bus')),
                ('from_stop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_from', to='routes.stop')),
                ('to_stop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_to', to='routes.stop')),
            ],
        ),
    ]
