# Generated by Django 4.2.29 on 2026-04-04 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickets', '0002_ticket_booking_ticket_seat'),
        ('inventory', '0001_initial'),
        ('operators', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TatkalQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(help_text='Matches aggregator source name', max_length=50)),
                ('source_trip_id', models.CharField(max_length=100)),
                ('is_open', models.BooleanField(default=False)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('seats_allocated', models.PositiveIntegerField()),
                ('seats_booked', models.PositiveIntegerField(default=0)),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tatkal_quotas', to='inventory.schedule')),
            ],
        ),
        migrations.CreateModel(
            name='TatkalConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('window_minutes_before', models.PositiveIntegerField(default=120)),
                ('surcharge_percent', models.DecimalField(decimal_places=2, default=25.0, max_digits=5)),
                ('quota_seats', models.PositiveIntegerField(default=5)),
                ('is_active', models.BooleanField(default=True)),
                ('operator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tatkal_config', to='operators.operator')),
            ],
        ),
        migrations.CreateModel(
            name='TatkalBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surcharge_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('quota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='tatkal.tatkalquota')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tatkal_bookings', to='tickets.ticket')),
            ],
        ),
    ]
