# Generated by Django 4.2.29 on 2026-04-04 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tatkal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tatkalquota',
            name='auto_open_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
