# Generated by Django 4.2.29 on 2026-07-04 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tatkal', '0002_tatkalquota_auto_open_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='tatkalbooking',
            name='dynamic_surcharge_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='AI-predicted surcharge percentage applied at booking time.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='tatkalbooking',
            name='predicted_demand_score',
            field=models.FloatField(blank=True, help_text='Raw ML demand score [0–10] at the time of booking.', null=True),
        ),
    ]
